management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      circuitbreakers:
        enabled: true
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true